### ISSUE TITLE
0.10.4: pytest is failing

### ISSUE THREAD

**Issue by kloczek** [flexmock/flexmock#42]
Just normal build, install and test cycle used on building package from non-root account:
- "setup.py build"
- "setup.py install --root </install/prefix>"
- "pytest with PYTHONPATH pointing to setearch and sitelib inside </install/prefix>
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.11, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/tkloczko/rpmbuild/BUILD/flexmock-0.10.4
plugins: forked-1.3.0, shutil-1.7.0, virtualenv-1.7.0, expect-1.1.0, httpbin-1.0.0, flake8-1.0.7, timeout-1.4.2, betamax-0.8.1, freezegun-0.4.2, case-1.5.3, isort-1.3.0, aspectlib-1.5.2, asyncio-0.15.1, toolbox-0.5, xprocess-0.17.1, aiohttp-0.3.0, checkdocs-2.7.0, mock-3.6.1, rerunfailures-9.1.1, requests-mock-1.9.3, cov-2.12.1, pyfakefs-4.5.0, flaky-3.7.0, hypothesis-6.14.0, benchmark-3.4.1, xdist-2.3.0, pylama-7.7.1, datadir-1.3.1, regressions-2.2.0, Faker-8.9.0, cases-3.6.2
collected 1016 items

. .                                                                                                                                                                  [  0%]
tests/flexmock_modern_test.py ....                                                                                                                                   [  0%]
tests/flexmock_nose_test.py .x.x............................................................................................................................FF...... [ 13%]
.........................................................FF......................................................................................................... [ 30%]
.................................                                                                                                                                    [ 33%]
tests/flexmock_pytest_test.py ...............................................................................................................................FF..... [ 46%]
..........................................................FF........................................................................................................ [ 62%]
..................................xXxx                                                                                                                               [ 66%]
tests/flexmock_test.py .........................FFF................................................................................................................. [ 80%]
..............................                                                                                                                                       [ 83%]
tests/flexmock_unittest_test.py .............................FF..................................................................................................... [ 96%]
.......................................                                                                                                                              [100%]

================================================================================= FAILURES =================================================================================
_______________________________________________________ TestRegularClass.test_flexmock_ordered_works_with_same_args ________________________________________________________

self = <flexmock_nose_test.TestRegularClass object at 0x7fc4001cdbb0>

    def test_flexmock_ordered_works_with_same_args(self):
        foo = flexmock()
        foo.should_receive('bar').ordered().and_return(1)
        foo.should_receive('bar').ordered().and_return(2)
>       a = foo.bar()

tests/flexmock_test.py:1378:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:951: in mock_method
    expectation = FlexmockContainer.get_flexmock_expectation(
../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:135: in get_flexmock_expectation
    cls._verify_call_order(found, args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'flexmock.FlexmockContainer'>, expectation = <flexmock.Expectation object at 0x7fc4003d2070>, args = {'kargs': (), 'kwargs': {}}

    @classmethod
    def _verify_call_order(cls, expectation, args):
        if not cls.ordered:
            next_method = cls.last
        else:
            next_method = cls.ordered.pop(0)
            cls.last = next_method
        if expectation is not next_method:
>           raise CallOrderError(
                '%s called before %s' %
                (_format_args(expectation.name, args),
                 _format_args(next_method.name, next_method.args)))
E           flexmock.CallOrderError: bar() called before bar("b")

../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:146: CallOrderError
______________________________________________ TestRegularClass.test_flexmock_ordered_works_with_same_args_after_default_stub ______________________________________________

self = <flexmock_nose_test.TestRegularClass object at 0x7fc400ad80d0>

    def test_flexmock_ordered_works_with_same_args_after_default_stub(self):
        foo = flexmock()
        foo.should_receive('bar').and_return(9)
        foo.should_receive('bar').ordered().and_return(1)
        foo.should_receive('bar').ordered().and_return(2)
>       a = foo.bar()

tests/flexmock_test.py:1388:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:951: in mock_method
    expectation = FlexmockContainer.get_flexmock_expectation(
../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:135: in get_flexmock_expectation
    cls._verify_call_order(found, args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'flexmock.FlexmockContainer'>, expectation = <flexmock.Expectation object at 0x7fc40038f580>, args = {'kargs': (), 'kwargs': {}}

    @classmethod
    def _verify_call_order(cls, expectation, args):
        if not cls.ordered:
            next_method = cls.last
        else:
            next_method = cls.ordered.pop(0)
            cls.last = next_method
        if expectation is not next_method:
>           raise CallOrderError(
                '%s called before %s' %
                (_format_args(expectation.name, args),
                 _format_args(next_method.name, next_method.args)))
E           flexmock.CallOrderError: bar() called before bar()

../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:146: CallOrderError
_______________________________________________________ TestUnittestClass.test_flexmock_ordered_works_with_same_args _______________________________________________________

self = <flexmock_nose_test.TestUnittestClass testMethod=test_flexmock_ordered_works_with_same_args>

    def test_flexmock_ordered_works_with_same_args(self):
        foo = flexmock()
        foo.should_receive('bar').ordered().and_return(1)
        foo.should_receive('bar').ordered().and_return(2)
>       a = foo.bar()

tests/flexmock_test.py:1378:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:951: in mock_method
    expectation = FlexmockContainer.get_flexmock_expectation(
../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:135: in get_flexmock_expectation
    cls._verify_call_order(found, args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'flexmock.FlexmockContainer'>, expectation = <flexmock.Expectation object at 0x7fc4000eb400>, args = {'kargs': (), 'kwargs': {}}

    @classmethod
    def _verify_call_order(cls, expectation, args):
        if not cls.ordered:
            next_method = cls.last
        else:
            next_method = cls.ordered.pop(0)
            cls.last = next_method
        if expectation is not next_method:
>           raise CallOrderError(
                '%s called before %s' %
                (_format_args(expectation.name, args),
                 _format_args(next_method.name, next_method.args)))
E           flexmock.CallOrderError: bar() called before bar("a")

../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:146: CallOrderError
_____________________________________________ TestUnittestClass.test_flexmock_ordered_works_with_same_args_after_default_stub ______________________________________________

self = <flexmock_nose_test.TestUnittestClass testMethod=test_flexmock_ordered_works_with_same_args_after_default_stub>

    def test_flexmock_ordered_works_with_same_args_after_default_stub(self):
        foo = flexmock()
        foo.should_receive('bar').and_return(9)
        foo.should_receive('bar').ordered().and_return(1)
        foo.should_receive('bar').ordered().and_return(2)
>       a = foo.bar()

tests/flexmock_test.py:1388:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:951: in mock_method
    expectation = FlexmockContainer.get_flexmock_expectation(
../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:135: in get_flexmock_expectation
    cls._verify_call_order(found, args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'flexmock.FlexmockContainer'>, expectation = <flexmock.Expectation object at 0x7fc4002c7130>, args = {'kargs': (), 'kwargs': {}}

    @classmethod
    def _verify_call_order(cls, expectation, args):
        if not cls.ordered:
            next_method = cls.last
        else:
            next_method = cls.ordered.pop(0)
            cls.last = next_method
        if expectation is not next_method:
>           raise CallOrderError(
                '%s called before %s' %
                (_format_args(expectation.name, args),
                 _format_args(next_method.name, next_method.args)))
E           flexmock.CallOrderError: bar() called before bar("b")

../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:146: CallOrderError
_________________________________________________________ TestForPytest.test_flexmock_ordered_works_with_same_args _________________________________________________________

self = <flexmock_pytest_test.TestForPytest object at 0x7fc400365160>

    def test_flexmock_ordered_works_with_same_args(self):
        foo = flexmock()
        foo.should_receive('bar').ordered().and_return(1)
        foo.should_receive('bar').ordered().and_return(2)
>       a = foo.bar()

tests/flexmock_test.py:1378:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:951: in mock_method
    expectation = FlexmockContainer.get_flexmock_expectation(
../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:135: in get_flexmock_expectation
    cls._verify_call_order(found, args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'flexmock.FlexmockContainer'>, expectation = <flexmock.Expectation object at 0x7fc4000568b0>, args = {'kargs': (), 'kwargs': {}}

    @classmethod
    def _verify_call_order(cls, expectation, args):
        if not cls.ordered:
            next_method = cls.last
        else:
            next_method = cls.ordered.pop(0)
            cls.last = next_method
        if expectation is not next_method:
>           raise CallOrderError(
                '%s called before %s' %
                (_format_args(expectation.name, args),
                 _format_args(next_method.name, next_method.args)))
E           flexmock.CallOrderError: bar() called before bar("b")

../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:146: CallOrderError
_______________________________________________ TestForPytest.test_flexmock_ordered_works_with_same_args_after_default_stub ________________________________________________

self = <flexmock_pytest_test.TestForPytest object at 0x7fc400226cd0>

    def test_flexmock_ordered_works_with_same_args_after_default_stub(self):
        foo = flexmock()
        foo.should_receive('bar').and_return(9)
        foo.should_receive('bar').ordered().and_return(1)
        foo.should_receive('bar').ordered().and_return(2)
>       a = foo.bar()

tests/flexmock_test.py:1388:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:951: in mock_method
    expectation = FlexmockContainer.get_flexmock_expectation(
../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:135: in get_flexmock_expectation
    cls._verify_call_order(found, args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'flexmock.FlexmockContainer'>, expectation = <flexmock.Expectation object at 0x7fc4001767c0>, args = {'kargs': (), 'kwargs': {}}

    @classmethod
    def _verify_call_order(cls, expectation, args):
        if not cls.ordered:
            next_method = cls.last
        else:
            next_method = cls.ordered.pop(0)
            cls.last = next_method
        if expectation is not next_method:
>           raise CallOrderError(
                '%s called before %s' %
                (_format_args(expectation.name, args),
                 _format_args(next_method.name, next_method.args)))
E           flexmock.CallOrderError: bar() called before bar()

../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:146: CallOrderError
_______________________________________________________ TestUnittestClass.test_flexmock_ordered_works_with_same_args _______________________________________________________

self = <flexmock_pytest_test.TestUnittestClass testMethod=test_flexmock_ordered_works_with_same_args>

    def test_flexmock_ordered_works_with_same_args(self):
        foo = flexmock()
        foo.should_receive('bar').ordered().and_return(1)
        foo.should_receive('bar').ordered().and_return(2)
>       a = foo.bar()

tests/flexmock_test.py:1378:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:951: in mock_method
    expectation = FlexmockContainer.get_flexmock_expectation(
../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:135: in get_flexmock_expectation
    cls._verify_call_order(found, args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'flexmock.FlexmockContainer'>, expectation = <flexmock.Expectation object at 0x7fc400067ee0>, args = {'kargs': (), 'kwargs': {}}

    @classmethod
    def _verify_call_order(cls, expectation, args):
        if not cls.ordered:
            next_method = cls.last
        else:
            next_method = cls.ordered.pop(0)
            cls.last = next_method
        if expectation is not next_method:
>           raise CallOrderError(
                '%s called before %s' %
                (_format_args(expectation.name, args),
                 _format_args(next_method.name, next_method.args)))
E           flexmock.CallOrderError: bar() called before bar("a")

../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:146: CallOrderError
_____________________________________________ TestUnittestClass.test_flexmock_ordered_works_with_same_args_after_default_stub ______________________________________________

self = <flexmock_pytest_test.TestUnittestClass testMethod=test_flexmock_ordered_works_with_same_args_after_default_stub>

    def test_flexmock_ordered_works_with_same_args_after_default_stub(self):
        foo = flexmock()
        foo.should_receive('bar').and_return(9)
        foo.should_receive('bar').ordered().and_return(1)
        foo.should_receive('bar').ordered().and_return(2)
>       a = foo.bar()

tests/flexmock_test.py:1388:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:951: in mock_method
    expectation = FlexmockContainer.get_flexmock_expectation(
../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:135: in get_flexmock_expectation
    cls._verify_call_order(found, args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'flexmock.FlexmockContainer'>, expectation = <flexmock.Expectation object at 0x7fc40022dd90>, args = {'kargs': (), 'kwargs': {}}

    @classmethod
    def _verify_call_order(cls, expectation, args):
        if not cls.ordered:
            next_method = cls.last
        else:
            next_method = cls.ordered.pop(0)
            cls.last = next_method
        if expectation is not next_method:
>           raise CallOrderError(
                '%s called before %s' %
                (_format_args(expectation.name, args),
                 _format_args(next_method.name, next_method.args)))
E           flexmock.CallOrderError: bar() called before bar("b")

../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:146: CallOrderError
_____________________________________________________ TestFlexmockUnittest.test_flexmock_ordered_works_with_same_args ______________________________________________________

self = <flexmock_test.TestFlexmockUnittest testMethod=test_flexmock_ordered_works_with_same_args>

    def test_flexmock_ordered_works_with_same_args(self):
        foo = flexmock()
        foo.should_receive('bar').ordered().and_return(1)
        foo.should_receive('bar').ordered().and_return(2)
>       a = foo.bar()

tests/flexmock_test.py:1378:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:951: in mock_method
    expectation = FlexmockContainer.get_flexmock_expectation(
../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:135: in get_flexmock_expectation
    cls._verify_call_order(found, args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'flexmock.FlexmockContainer'>, expectation = <flexmock.Expectation object at 0x7fc3fffb7f40>, args = {'kargs': (), 'kwargs': {}}

    @classmethod
    def _verify_call_order(cls, expectation, args):
        if not cls.ordered:
            next_method = cls.last
        else:
            next_method = cls.ordered.pop(0)
            cls.last = next_method
        if expectation is not next_method:
>           raise CallOrderError(
                '%s called before %s' %
                (_format_args(expectation.name, args),
                 _format_args(next_method.name, next_method.args)))
E           flexmock.CallOrderError: bar() called before bar("a")

../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:146: CallOrderError
____________________________________________ TestFlexmockUnittest.test_flexmock_ordered_works_with_same_args_after_default_stub ____________________________________________

self = <flexmock_test.TestFlexmockUnittest testMethod=test_flexmock_ordered_works_with_same_args_after_default_stub>

    def test_flexmock_ordered_works_with_same_args_after_default_stub(self):
        foo = flexmock()
        foo.should_receive('bar').and_return(9)
        foo.should_receive('bar').ordered().and_return(1)
        foo.should_receive('bar').ordered().and_return(2)
>       a = foo.bar()

tests/flexmock_test.py:1388:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:951: in mock_method
    expectation = FlexmockContainer.get_flexmock_expectation(
../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:135: in get_flexmock_expectation
    cls._verify_call_order(found, args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'flexmock.FlexmockContainer'>, expectation = <flexmock.Expectation object at 0x7fc3fff5a4f0>, args = {'kargs': (), 'kwargs': {}}

    @classmethod
    def _verify_call_order(cls, expectation, args):
        if not cls.ordered:
            next_method = cls.last
        else:
            next_method = cls.ordered.pop(0)
            cls.last = next_method
        if expectation is not next_method:
>           raise CallOrderError(
                '%s called before %s' %
                (_format_args(expectation.name, args),
                 _format_args(next_method.name, next_method.args)))
E           flexmock.CallOrderError: bar() called before bar("b")

../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:146: CallOrderError
_____________________________________________ TestFlexmockUnittest.test_flexmock_preserves_stubbed_class_methods_between_tests _____________________________________________

self = <flexmock_test.TestFlexmockUnittest testMethod=test_flexmock_preserves_stubbed_class_methods_between_tests>

    def test_flexmock_preserves_stubbed_class_methods_between_tests(self):
        class User:
            def get_name(self):
                return 'mike'
        user = User()
        flexmock(User).should_receive('get_name').and_return('john')
        assertEqual('john', user.get_name())
>       self._tear_down()

tests/flexmock_test.py:343:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/flexmock_test.py:1798: in _tear_down
    return flexmock_teardown()
../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:1187: in flexmock_teardown
    _getattr(expectation, 'verify')()
../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:617: in verify
    self.__raise(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <flexmock.Expectation object at 0x7fc3fff6feb0>, exception = <class 'flexmock.MethodCallError'>
message = 'foo() expected to be called exactly 1 times, called 0 times'

    def __raise(self, exception, message):
        """Safe internal raise implementation.

        In case we're patching builtins, it's important to reset the
        expectation before raising any exceptions or else things like
        open() might be stubbed out and the resulting runner errors are very
        difficult to diagnose.
        """
        self.reset()
>       raise exception(message)
E       flexmock.MethodCallError: foo() expected to be called exactly 1 times, called 0 times

../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:349: MethodCallError
_____________________________________________________ TestFlexmockUnittest.test_flexmock_ordered_works_with_same_args ______________________________________________________

self = <flexmock_test.TestFlexmockUnittest testMethod=test_flexmock_ordered_works_with_same_args>

    def test_flexmock_ordered_works_with_same_args(self):
        foo = flexmock()
        foo.should_receive('bar').ordered().and_return(1)
        foo.should_receive('bar').ordered().and_return(2)
>       a = foo.bar()

tests/flexmock_test.py:1378:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:951: in mock_method
    expectation = FlexmockContainer.get_flexmock_expectation(
../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:135: in get_flexmock_expectation
    cls._verify_call_order(found, args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'flexmock.FlexmockContainer'>, expectation = <flexmock.Expectation object at 0x7fc3ffc15a60>, args = {'kargs': (), 'kwargs': {}}

    @classmethod
    def _verify_call_order(cls, expectation, args):
        if not cls.ordered:
            next_method = cls.last
        else:
            next_method = cls.ordered.pop(0)
            cls.last = next_method
        if expectation is not next_method:
>           raise CallOrderError(
                '%s called before %s' %
                (_format_args(expectation.name, args),
                 _format_args(next_method.name, next_method.args)))
E           flexmock.CallOrderError: bar() called before bar("a")

../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:146: CallOrderError
____________________________________________ TestFlexmockUnittest.test_flexmock_ordered_works_with_same_args_after_default_stub ____________________________________________

self = <flexmock_test.TestFlexmockUnittest testMethod=test_flexmock_ordered_works_with_same_args_after_default_stub>

    def test_flexmock_ordered_works_with_same_args_after_default_stub(self):
        foo = flexmock()
        foo.should_receive('bar').and_return(9)
        foo.should_receive('bar').ordered().and_return(1)
        foo.should_receive('bar').ordered().and_return(2)
>       a = foo.bar()

tests/flexmock_test.py:1388:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:951: in mock_method
    expectation = FlexmockContainer.get_flexmock_expectation(
../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:135: in get_flexmock_expectation
    cls._verify_call_order(found, args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'flexmock.FlexmockContainer'>, expectation = <flexmock.Expectation object at 0x7fc400112e50>, args = {'kargs': (), 'kwargs': {}}

    @classmethod
    def _verify_call_order(cls, expectation, args):
        if not cls.ordered:
            next_method = cls.last
        else:
            next_method = cls.ordered.pop(0)
            cls.last = next_method
        if expectation is not next_method:
>           raise CallOrderError(
                '%s called before %s' %
                (_format_args(expectation.name, args),
                 _format_args(next_method.name, next_method.args)))
E           flexmock.CallOrderError: bar() called before bar("b")

../../BUILDROOT/python-flexmock-0.10.4-12.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock.py:146: CallOrderError
============================================================================= warnings summary =============================================================================
tests/flexmock_nose_test.py:14
  tests/flexmock_nose_test.py:14: PytestCollectionWarning: yield tests were removed in pytest 4.0 - test_module_level_generator will be ignored
    def test_module_level_generator():

tests/flexmock_nose_test.py:27
  tests/flexmock_nose_test.py:27: PytestCollectionWarning: yield tests were removed in pytest 4.0 - test_class_level_generator_tests will be ignored
    def test_class_level_generator_tests(self):

tests/flexmock_pytest_test.py:9
  /home/tkloczko/rpmbuild/BUILD/flexmock-0.10.4/tests/flexmock_pytest_test.py:9: PytestUnknownMarkWarning: Unknown pytest.mark.pytest - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    pytestmark = pytest.mark.pytest

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================= short test summary info ==========================================================================
XFAIL tests/flexmock_nose_test.py::test_module_level_generator
  reason: [NOTRUN] yield tests were removed in pytest 4.0 - test_module_level_generator will be ignored
XFAIL tests/flexmock_nose_test.py::TestRegularClass::test_class_level_generator_tests
  reason: [NOTRUN] yield tests were removed in pytest 4.0 - test_class_level_generator_tests will be ignored
XFAIL tests/flexmock_pytest_test.py::TestFailureOnException::test_exception
XFAIL tests/flexmock_pytest_test.py::TestFailureOnException::test_flexmock_doesnt_override_existing_exception
XFAIL tests/flexmock_pytest_test.py::TestFailureOnException::test_flexmock_doesnt_override_assertion
XPASS tests/flexmock_pytest_test.py::TestFailureOnException::test_flexmock_raises_if_no_exception
FAILED tests/flexmock_nose_test.py::TestRegularClass::test_flexmock_ordered_works_with_same_args - flexmock.CallOrderError: bar() called before bar("b")
FAILED tests/flexmock_nose_test.py::TestRegularClass::test_flexmock_ordered_works_with_same_args_after_default_stub - flexmock.CallOrderError: bar() called before bar()
FAILED tests/flexmock_nose_test.py::TestUnittestClass::test_flexmock_ordered_works_with_same_args - flexmock.CallOrderError: bar() called before bar("a")
FAILED tests/flexmock_nose_test.py::TestUnittestClass::test_flexmock_ordered_works_with_same_args_after_default_stub - flexmock.CallOrderError: bar() called before bar("b")
FAILED tests/flexmock_pytest_test.py::TestForPytest::test_flexmock_ordered_works_with_same_args - flexmock.CallOrderError: bar() called before bar("b")
FAILED tests/flexmock_pytest_test.py::TestForPytest::test_flexmock_ordered_works_with_same_args_after_default_stub - flexmock.CallOrderError: bar() called before bar()
FAILED tests/flexmock_pytest_test.py::TestUnittestClass::test_flexmock_ordered_works_with_same_args - flexmock.CallOrderError: bar() called before bar("a")
FAILED tests/flexmock_pytest_test.py::TestUnittestClass::test_flexmock_ordered_works_with_same_args_after_default_stub - flexmock.CallOrderError: bar() called before bar...
FAILED tests/flexmock_test.py::TestFlexmockUnittest::test_flexmock_ordered_works_with_same_args - flexmock.CallOrderError: bar() called before bar("a")
FAILED tests/flexmock_test.py::TestFlexmockUnittest::test_flexmock_ordered_works_with_same_args_after_default_stub - flexmock.CallOrderError: bar() called before bar("b")
FAILED tests/flexmock_test.py::TestFlexmockUnittest::test_flexmock_preserves_stubbed_class_methods_between_tests - flexmock.MethodCallError: foo() expected to be called ...
FAILED tests/flexmock_unittest_test.py::TestFlexmockUnittest::test_flexmock_ordered_works_with_same_args - flexmock.CallOrderError: bar() called before bar("a")
FAILED tests/flexmock_unittest_test.py::TestFlexmockUnittest::test_flexmock_ordered_works_with_same_args_after_default_stub - flexmock.CallOrderError: bar() called befor...
===================================================== 13 failed, 997 passed, 5 xfailed, 1 xpassed, 3 warnings in 9.68s =====================================================
```

**Comment by christophe-riolo** [comment]
Hello,
we're a small team who are currently trying to claim maintenance of this project as is has not seen much movement lately, can you check if you get the same errors with our fork ? https://github.com/flexmock/flexmock

**Comment by kloczek** [comment]
> Hello,
> we're a small team who are currently trying to claim maintenance of this project as is has not seen much movement lately, can you check if you get the same errors with our fork ? https://github.com/flexmock/flexmock

Using my automation it would be easier to have some git tag in that repo.

**Comment by christophe-riolo** [comment]
Sure, we're on tag 0.10.7 : https://github.com/flexmock/flexmock/tree/0.10.7

**Comment by kloczek** [comment]
> Sure, we're on tag 0.10.7 : https://github.com/flexmock/flexmock/tree/0.10.7

I see that in that version you moved away from setuptools :(
setuptools provides nice feature which allows build documentation without care whre is `copy.py` by `/usr/bin/python3 setup.py build_sphinx -b [man|html]`
IMO moving to `builder` based framework from that point of view is kind of huge step back :(
And `builder` produces only .whl files which is necessary to unpack/install before generate documentation or test.

After quic adaptation of my spec to be able execute pytest I see that it fails
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-flexmock-0.10.7-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-flexmock-0.10.7-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.11, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/tkloczko/rpmbuild/BUILD/flexmock-0.10.7
plugins: forked-1.3.0, shutil-1.7.0, virtualenv-1.7.0, expect-1.1.0, httpbin-1.0.0, flake8-1.0.7, timeout-1.4.2, betamax-0.8.1, freezegun-0.4.2, case-1.5.3, isort-1.3.0, aspectlib-1.5.2, asyncio-0.15.1, toolbox-0.5, xprocess-0.17.1, aiohttp-0.3.0, checkdocs-2.7.0, mock-3.6.1, rerunfailures-9.1.1, requests-mock-1.9.3, cov-2.12.1, pyfakefs-4.5.0, flaky-3.7.0, hypothesis-6.14.0, benchmark-3.4.1, xdist-2.3.0, pylama-7.7.1, datadir-1.3.1, regressions-2.2.0, Faker-8.9.0, cases-3.6.2
collected 512 items

. .                                                                                                                                                                  [  0%]
tests/flexmock_pytest_test.py ...............................................................................................................................FF..... [ 26%]
..........................................................FF........................................................................................................ [ 58%]
..................................xXxx                                                                                                                               [ 65%]
tests/flexmock_test.py .........................FFF................................................................................................................. [ 93%]
..................................                                                                                                                                   [100%]

================================================================================= FAILURES =================================================================================
_________________________________________________________ TestForPytest.test_flexmock_ordered_works_with_same_args _________________________________________________________

self = <tests.flexmock_pytest_test.TestForPytest object at 0x7f755af55850>

    def test_flexmock_ordered_works_with_same_args(self):
        foo = flexmock()
        foo.should_receive("bar").ordered().and_return(1)
        foo.should_receive("bar").ordered().and_return(2)
>       a = foo.bar()

tests/flexmock_test.py:1448:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../BUILDROOT/python-flexmock-0.10.7-2.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock/api.py:413: in mock_method
    expectation = FlexmockContainer.get_flexmock_expectation(self, name, arguments)
../../BUILDROOT/python-flexmock-0.10.7-2.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock/api.py:1023: in get_flexmock_expectation
    cls._verify_call_order(found, args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'flexmock.api.FlexmockContainer'>, expectation = <flexmock.api.Expectation object at 0x7f755af631c0>, args = {'kargs': (), 'kwargs': {}}

    @classmethod
    def _verify_call_order(cls, expectation: Expectation, args: Dict[str, Any]) -> None:
        if not cls.ordered:
            next_method = cls.last
        else:
            next_method = cls.ordered.pop(0)
            cls.last = next_method
        if expectation is not next_method and next_method is not None:
>           raise CallOrderError(
                "%s called before %s"
                % (
                    _format_args(str(expectation.name), args),
                    _format_args(str(next_method.name), next_method._args),
                )
            )
E           flexmock.exceptions.CallOrderError: bar() called before bar("b")

../../BUILDROOT/python-flexmock-0.10.7-2.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock/api.py:1035: CallOrderError
_______________________________________________ TestForPytest.test_flexmock_ordered_works_with_same_args_after_default_stub ________________________________________________

self = <tests.flexmock_pytest_test.TestForPytest object at 0x7f755b1922b0>

    def test_flexmock_ordered_works_with_same_args_after_default_stub(self):
        foo = flexmock()
        foo.should_receive("bar").and_return(9)
        foo.should_receive("bar").ordered().and_return(1)
        foo.should_receive("bar").ordered().and_return(2)
>       a = foo.bar()

tests/flexmock_test.py:1458:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../BUILDROOT/python-flexmock-0.10.7-2.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock/api.py:413: in mock_method
    expectation = FlexmockContainer.get_flexmock_expectation(self, name, arguments)
../../BUILDROOT/python-flexmock-0.10.7-2.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock/api.py:1023: in get_flexmock_expectation
    cls._verify_call_order(found, args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'flexmock.api.FlexmockContainer'>, expectation = <flexmock.api.Expectation object at 0x7f755b040370>, args = {'kargs': (), 'kwargs': {}}

    @classmethod
    def _verify_call_order(cls, expectation: Expectation, args: Dict[str, Any]) -> None:
        if not cls.ordered:
            next_method = cls.last
        else:
            next_method = cls.ordered.pop(0)
            cls.last = next_method
        if expectation is not next_method and next_method is not None:
>           raise CallOrderError(
                "%s called before %s"
                % (
                    _format_args(str(expectation.name), args),
                    _format_args(str(next_method.name), next_method._args),
                )
            )
E           flexmock.exceptions.CallOrderError: bar() called before bar()

../../BUILDROOT/python-flexmock-0.10.7-2.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock/api.py:1035: CallOrderError
_______________________________________________________ TestUnittestClass.test_flexmock_ordered_works_with_same_args _______________________________________________________

self = <tests.flexmock_pytest_test.TestUnittestClass testMethod=test_flexmock_ordered_works_with_same_args>

    def test_flexmock_ordered_works_with_same_args(self):
        foo = flexmock()
        foo.should_receive("bar").ordered().and_return(1)
        foo.should_receive("bar").ordered().and_return(2)
>       a = foo.bar()

tests/flexmock_test.py:1448:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../BUILDROOT/python-flexmock-0.10.7-2.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock/api.py:413: in mock_method
    expectation = FlexmockContainer.get_flexmock_expectation(self, name, arguments)
../../BUILDROOT/python-flexmock-0.10.7-2.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock/api.py:1023: in get_flexmock_expectation
    cls._verify_call_order(found, args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'flexmock.api.FlexmockContainer'>, expectation = <flexmock.api.Expectation object at 0x7f755b159eb0>, args = {'kargs': (), 'kwargs': {}}

    @classmethod
    def _verify_call_order(cls, expectation: Expectation, args: Dict[str, Any]) -> None:
        if not cls.ordered:
            next_method = cls.last
        else:
            next_method = cls.ordered.pop(0)
            cls.last = next_method
        if expectation is not next_method and next_method is not None:
>           raise CallOrderError(
                "%s called before %s"
                % (
                    _format_args(str(expectation.name), args),
                    _format_args(str(next_method.name), next_method._args),
                )
            )
E           flexmock.exceptions.CallOrderError: bar() called before bar("a")

../../BUILDROOT/python-flexmock-0.10.7-2.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock/api.py:1035: CallOrderError
_____________________________________________ TestUnittestClass.test_flexmock_ordered_works_with_same_args_after_default_stub ______________________________________________

self = <tests.flexmock_pytest_test.TestUnittestClass testMethod=test_flexmock_ordered_works_with_same_args_after_default_stub>

    def test_flexmock_ordered_works_with_same_args_after_default_stub(self):
        foo = flexmock()
        foo.should_receive("bar").and_return(9)
        foo.should_receive("bar").ordered().and_return(1)
        foo.should_receive("bar").ordered().and_return(2)
>       a = foo.bar()

tests/flexmock_test.py:1458:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../BUILDROOT/python-flexmock-0.10.7-2.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock/api.py:413: in mock_method
    expectation = FlexmockContainer.get_flexmock_expectation(self, name, arguments)
../../BUILDROOT/python-flexmock-0.10.7-2.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock/api.py:1023: in get_flexmock_expectation
    cls._verify_call_order(found, args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'flexmock.api.FlexmockContainer'>, expectation = <flexmock.api.Expectation object at 0x7f755b14e3d0>, args = {'kargs': (), 'kwargs': {}}

    @classmethod
    def _verify_call_order(cls, expectation: Expectation, args: Dict[str, Any]) -> None:
        if not cls.ordered:
            next_method = cls.last
        else:
            next_method = cls.ordered.pop(0)
            cls.last = next_method
        if expectation is not next_method and next_method is not None:
>           raise CallOrderError(
                "%s called before %s"
                % (
                    _format_args(str(expectation.name), args),
                    _format_args(str(next_method.name), next_method._args),
                )
            )
E           flexmock.exceptions.CallOrderError: bar() called before bar("b")

../../BUILDROOT/python-flexmock-0.10.7-2.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock/api.py:1035: CallOrderError
_____________________________________________________ TestFlexmockUnittest.test_flexmock_ordered_works_with_same_args ______________________________________________________

self = <tests.flexmock_test.TestFlexmockUnittest testMethod=test_flexmock_ordered_works_with_same_args>

    def test_flexmock_ordered_works_with_same_args(self):
        foo = flexmock()
        foo.should_receive("bar").ordered().and_return(1)
        foo.should_receive("bar").ordered().and_return(2)
>       a = foo.bar()

tests/flexmock_test.py:1448:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../BUILDROOT/python-flexmock-0.10.7-2.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock/api.py:413: in mock_method
    expectation = FlexmockContainer.get_flexmock_expectation(self, name, arguments)
../../BUILDROOT/python-flexmock-0.10.7-2.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock/api.py:1023: in get_flexmock_expectation
    cls._verify_call_order(found, args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'flexmock.api.FlexmockContainer'>, expectation = <flexmock.api.Expectation object at 0x7f755ad10400>, args = {'kargs': (), 'kwargs': {}}

    @classmethod
    def _verify_call_order(cls, expectation: Expectation, args: Dict[str, Any]) -> None:
        if not cls.ordered:
            next_method = cls.last
        else:
            next_method = cls.ordered.pop(0)
            cls.last = next_method
        if expectation is not next_method and next_method is not None:
>           raise CallOrderError(
                "%s called before %s"
                % (
                    _format_args(str(expectation.name), args),
                    _format_args(str(next_method.name), next_method._args),
                )
            )
E           flexmock.exceptions.CallOrderError: bar() called before bar("a")

../../BUILDROOT/python-flexmock-0.10.7-2.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock/api.py:1035: CallOrderError
____________________________________________ TestFlexmockUnittest.test_flexmock_ordered_works_with_same_args_after_default_stub ____________________________________________

self = <tests.flexmock_test.TestFlexmockUnittest testMethod=test_flexmock_ordered_works_with_same_args_after_default_stub>

    def test_flexmock_ordered_works_with_same_args_after_default_stub(self):
        foo = flexmock()
        foo.should_receive("bar").and_return(9)
        foo.should_receive("bar").ordered().and_return(1)
        foo.should_receive("bar").ordered().and_return(2)
>       a = foo.bar()

tests/flexmock_test.py:1458:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../BUILDROOT/python-flexmock-0.10.7-2.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock/api.py:413: in mock_method
    expectation = FlexmockContainer.get_flexmock_expectation(self, name, arguments)
../../BUILDROOT/python-flexmock-0.10.7-2.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock/api.py:1023: in get_flexmock_expectation
    cls._verify_call_order(found, args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'flexmock.api.FlexmockContainer'>, expectation = <flexmock.api.Expectation object at 0x7f755ac1fc70>, args = {'kargs': (), 'kwargs': {}}

    @classmethod
    def _verify_call_order(cls, expectation: Expectation, args: Dict[str, Any]) -> None:
        if not cls.ordered:
            next_method = cls.last
        else:
            next_method = cls.ordered.pop(0)
            cls.last = next_method
        if expectation is not next_method and next_method is not None:
>           raise CallOrderError(
                "%s called before %s"
                % (
                    _format_args(str(expectation.name), args),
                    _format_args(str(next_method.name), next_method._args),
                )
            )
E           flexmock.exceptions.CallOrderError: bar() called before bar("b")

../../BUILDROOT/python-flexmock-0.10.7-2.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock/api.py:1035: CallOrderError
_____________________________________________ TestFlexmockUnittest.test_flexmock_preserves_stubbed_class_methods_between_tests _____________________________________________

self = <tests.flexmock_test.TestFlexmockUnittest testMethod=test_flexmock_preserves_stubbed_class_methods_between_tests>

    def test_flexmock_preserves_stubbed_class_methods_between_tests(self):
        class User:
            def get_name(self):
                return "mike"

        user = User()
        flexmock(User).should_receive("get_name").and_return("john")
        assert_equal("john", user.get_name())
>       self._tear_down()

tests/flexmock_test.py:352:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/flexmock_test.py:1893: in _tear_down
    return flexmock_teardown()
../../BUILDROOT/python-flexmock-0.10.7-2.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock/api.py:473: in flexmock_teardown
    _getattr(expectation, "verify")()
../../BUILDROOT/python-flexmock-0.10.7-2.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock/api.py:936: in verify
    self.__raise(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <flexmock.api.Expectation object at 0x7f755adc9280>, exception = <class 'flexmock.exceptions.MethodCallError'>
message = 'foo() expected to be called exactly 1 times, called 0 times'

    def __raise(self, exception: Type[Exception], message: str) -> NoReturn:
        """Safe internal raise implementation.

        In case we're patching builtins, it's important to reset the
        expectation before raising any exceptions or else things like
        open() might be stubbed out and the resulting runner errors are very
        difficult to diagnose.
        """
        self.reset()
>       raise exception(message)
E       flexmock.exceptions.MethodCallError: foo() expected to be called exactly 1 times, called 0 times

../../BUILDROOT/python-flexmock-0.10.7-2.fc35.x86_64/usr/lib/python3.8/site-packages/flexmock/api.py:669: MethodCallError
========================================================================= short test summary info ==========================================================================
XFAIL tests/flexmock_pytest_test.py::TestFailureOnException::test_exception
XFAIL tests/flexmock_pytest_test.py::TestFailureOnException::test_flexmock_doesnt_override_existing_exception
XFAIL tests/flexmock_pytest_test.py::TestFailureOnException::test_flexmock_doesnt_override_assertion
XPASS tests/flexmock_pytest_test.py::TestFailureOnException::test_flexmock_raises_if_no_exception
FAILED tests/flexmock_pytest_test.py::TestForPytest::test_flexmock_ordered_works_with_same_args - flexmock.exceptions.CallOrderError: bar() called before bar("b")
FAILED tests/flexmock_pytest_test.py::TestForPytest::test_flexmock_ordered_works_with_same_args_after_default_stub - flexmock.exceptions.CallOrderError: bar() called bef...
FAILED tests/flexmock_pytest_test.py::TestUnittestClass::test_flexmock_ordered_works_with_same_args - flexmock.exceptions.CallOrderError: bar() called before bar("a")
FAILED tests/flexmock_pytest_test.py::TestUnittestClass::test_flexmock_ordered_works_with_same_args_after_default_stub - flexmock.exceptions.CallOrderError: bar() called...
FAILED tests/flexmock_test.py::TestFlexmockUnittest::test_flexmock_ordered_works_with_same_args - flexmock.exceptions.CallOrderError: bar() called before bar("a")
FAILED tests/flexmock_test.py::TestFlexmockUnittest::test_flexmock_ordered_works_with_same_args_after_default_stub - flexmock.exceptions.CallOrderError: bar() called bef...
FAILED tests/flexmock_test.py::TestFlexmockUnittest::test_flexmock_preserves_stubbed_class_methods_between_tests - flexmock.exceptions.MethodCallError: foo() expected to...
=========================================================== 7 failed, 501 passed, 3 xfailed, 1 xpassed in 5.28s ============================================================
```

**Comment by kloczek** [comment]
There are as well some issues with using Sphinx 4.0.2
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-flexmock-0.10.7-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ sphinx-build -b man -d python-flexmock docs .
Running Sphinx v4.0.2
WARNING: html_static_path entry '_static' does not exist
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 6 added, 0 changed, 0 removed
reading sources... [100%] user-guide
WARNING: autodoc: failed to import class 'Mock' from module 'flexmock'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/util/inspect.py", line 412, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'flexmock' has no attribute 'Mock'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 110, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 318, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2606, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python3.8/site-packages/sphinx/util/inspect.py", line 428, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: Mock

WARNING: autodoc: failed to import class 'Expectation' from module 'flexmock'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/util/inspect.py", line 412, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'flexmock' has no attribute 'Expectation'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 110, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 318, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2606, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/usr/lib/python3.8/site-packages/sphinx/util/inspect.py", line 428, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: Expectation

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-flexmock.3 { start user-guide api changelog compare } done
build succeeded, 3 warnings.
```

**Comment by christophe-riolo** [comment]
Right, thanks for the report, we haven't gotten into the documentation yet, we'll look into that :)

**Comment by christophe-riolo** [comment]
Hello,
It should now be fixed with version `0.10.7+1` !

**Comment by ollipa** [comment]
@kloczek, can you still reproduce this issue with the latest version in master branch?

**Comment by kloczek** [comment]
Jusyt checked 0.10.8 and pytest is OK now.
There are some warnings but no fails.
Feel free to close this ticket.

Thank you :)
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-flexmock-0.10.8-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-flexmock-0.10.8-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.11, pytest-6.2.5, py-1.10.0, pluggy-0.13.1
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
Using --randomly-seed=1292634805
rootdir: /home/tkloczko/rpmbuild/BUILD/flexmock-0.10.8
plugins: forked-1.3.0, shutil-1.7.0, virtualenv-1.7.0, expect-1.1.0, flake8-1.0.7, timeout-1.4.2, betamax-0.8.1, freezegun-0.4.2, aspectlib-1.5.2, toolbox-0.5, rerunfailures-9.1.1, requests-mock-1.9.3, cov-2.12.1, flaky-3.7.0, benchmark-3.4.1, xdist-2.3.0, pylama-7.7.1, datadir-1.3.1, regressions-2.2.0, cases-3.6.3, xprocess-0.18.1, black-0.3.12, anyio-3.3.0, asyncio-0.15.1, trio-0.7.0, subtests-0.5.0, isort-2.0.0, hypothesis-6.14.6, mock-3.6.1, profiling-1.7.0, randomly-3.8.0, Faker-8.12.1, nose2pytest-1.0.8, pyfakefs-4.5.1, tornado-0.8.1
collected 1039 items

tests/flexmock_unittest_test.py .................................................................................................................................... [ 12%]
...........................................                                                                                                                          [ 16%]
tests/flexmock_modern_test.py ....                                                                                                                                   [ 17%]
tests/flexmock_nose_test.py ........................................................................................................................................ [ 30%]
.................................................................................................................x....................................x............. [ 46%]
.........................................                                                                                                                            [ 50%]
tests/flexmock_test.py ............................................................................................................................................. [ 63%]
..................................                                                                                                                                   [ 66%]
tests/flexmock_pytest_test.py ...................................................................................................................................... [ 79%]
.................................................................................................................................................................... [ 95%]
..........................................xxxx                                                                                                                       [100%]

============================================================================= warnings summary =============================================================================
tests/flexmock_nose_test.py:14
  tests/flexmock_nose_test.py:14: PytestCollectionWarning: yield tests were removed in pytest 4.0 - test_module_level_generator will be ignored
    def test_module_level_generator():

tests/flexmock_nose_test.py:27
  tests/flexmock_nose_test.py:27: PytestCollectionWarning: yield tests were removed in pytest 4.0 - test_class_level_generator_tests will be ignored
    def test_class_level_generator_tests(self):

tests/flexmock_pytest_test.py:9
  /home/tkloczko/rpmbuild/BUILD/flexmock-0.10.8/tests/flexmock_pytest_test.py:9: PytestUnknownMarkWarning: Unknown pytest.mark.pytest - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    pytestmark = pytest.mark.pytest

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================= short test summary info ==========================================================================
XFAIL tests/flexmock_nose_test.py::test_module_level_generator
  reason: [NOTRUN] yield tests were removed in pytest 4.0 - test_module_level_generator will be ignored
XFAIL tests/flexmock_nose_test.py::TestRegularClass::test_class_level_generator_tests
  reason: [NOTRUN] yield tests were removed in pytest 4.0 - test_class_level_generator_tests will be ignored
XFAIL tests/flexmock_pytest_test.py::TestFailureOnException::test_exception
XFAIL tests/flexmock_pytest_test.py::TestFailureOnException::test_flexmock_doesnt_override_existing_exception
XFAIL tests/flexmock_pytest_test.py::TestFailureOnException::test_flexmock_doesnt_override_assertion
XFAIL tests/flexmock_pytest_test.py::TestFailureOnException::test_flexmock_raises_if_no_exception
=============================================================== 1033 passed, 6 xfailed, 3 warnings in 3.19s ================================================================
pytest-xprocess reminder::Be sure to terminate the started process by running 'pytest --xkill' if you have not explicitly done so in your fixture with 'xprocess.getinfo(<process_name>).terminate()'.
```
